// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp39vf-j2TDTwmNknYDLmqZJ3VvEjpB0Q',
    appId: '1:1077938321371:web:7135d092fee7e1ab0ed9fe',
    messagingSenderId: '1077938321371',
    projectId: 'minhapm-5ff71',
    authDomain: 'minhapm-5ff71.firebaseapp.com',
    storageBucket: 'minhapm-5ff71.appspot.com',
    measurementId: 'G-ES7W3ERL12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIyyIvcQmmPTdkgc6ufopYuCHgz9DZYjA',
    appId: '1:1077938321371:android:5e7798becbdb20440ed9fe',
    messagingSenderId: '1077938321371',
    projectId: 'minhapm-5ff71',
    storageBucket: 'minhapm-5ff71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASba7sfDtkxHq64NPkirZWFo7NEMuwrcA',
    appId: '1:1077938321371:ios:edc8c9cdbb1d68540ed9fe',
    messagingSenderId: '1077938321371',
    projectId: 'minhapm-5ff71',
    storageBucket: 'minhapm-5ff71.appspot.com',
    iosClientId: '1077938321371-e1mra0mpspdt4dsnr3n0qe9i04ed3ofd.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASba7sfDtkxHq64NPkirZWFo7NEMuwrcA',
    appId: '1:1077938321371:ios:edc8c9cdbb1d68540ed9fe',
    messagingSenderId: '1077938321371',
    projectId: 'minhapm-5ff71',
    storageBucket: 'minhapm-5ff71.appspot.com',
    iosClientId: '1077938321371-e1mra0mpspdt4dsnr3n0qe9i04ed3ofd.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhmobile',
  );
}
